#pragma once

enum class TextureCode {
  TEX_BLANK = 0,
  TEX_ARROW_UP,
  TEX_ARROW_DOWN,
  TEX_ARROW_LEFT,
  TEX_ARROW_RIGHT,
  TEX_TRAP,
  TEX_TURRET,
  TEX_TRAP_SHOP,
  TEX_CANDY,
  TEX_MONEY,
  TEX_FACTORY,
  TEX_LOG,
  TEX_LOG_SHADOW,
  TEX_KING_ROCK,
  TEX_KING_ROCK_SHADOW,
  TEX_CONSTRUCTION_SITE,
  TEX_TURRET_SHOP,
  TEX_HUD_HEALTH,
  TEX_HUD_COINS,
  TEX_DIGIT_0,
  TEX_DIGIT_1,
  TEX_DIGIT_2,
  TEX_DIGIT_3,
  TEX_DIGIT_4,
  TEX_DIGIT_5,
  TEX_DIGIT_6,
  TEX_DIGIT_7,
  TEX_DIGIT_8,
  TEX_DIGIT_9,
  GAME_OVER_SCREEN,
  TEX_TIME_UNTIL,
  // Add a new texture above this line
  TEX_NUM_TEXTURES,
  INVALID
};

namespace texture {

void load();

}
